name: fluttery
description: Flutter package that helps with prototyping.
version: 0.0.8
author: ammaugost@gmail.com>
homepage: https://github.com/Mtellect/fluttery

environment:
  sdk: '>=1.8.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.3.2